export { Hero } from './Hero'
export { Services } from './Services'
export { About } from './About'
export { Projects } from './Projects'
export { Testimonials } from './Testimonials'
export { CTA } from './CTA'
export { FeatureBanner } from './FeatureBanner'
